name: MetaDataHelper
version: '${project.version}'
main: main.mdh.MetaDataHelper
api-version: 1.19
commands:
  metadata:
    description: "Allows you to view/modify MetaData in the selected block using the right mouse button."